### ISSUE TITLE
Cannot work with sveltekit deployed to deno

### ISSUE THREAD

**Issue by yangg** [wobsoriano/svelte-sonner#51]
### Describe the bug

```
TypeError: window.matchMedia is not a function
    at file:///src/server.js:1105:20
    at Object.$$render (file:///src/server.js:184:18)
    at file:///src/server.js:1174:55
```
```
$: {
    if (theme !== 'system') {
        actualTheme = theme;
    }
    if (typeof window !== 'undefined') {
        if (theme === 'system') {
            // check if current preference is dark
            if (window.matchMedia &&
                window.matchMedia('(prefers-color-scheme: dark)').matches) {
                // it's currently dark
                actualTheme = 'dark';
            }
            else {
                // it's not dark
                actualTheme = 'light';
            }
        }
 //  next line is 1105
        window
            .matchMedia('(prefers-color-scheme: dark)')
            .addEventListener('change', ({ matches }) => {
            actualTheme = matches ? 'dark' : 'light';
        });
    }
}
```

### Reproduction

deploy to deno

### System Info

```bash
1
```

### Severity

annoyance

**Comment by wobsoriano** [comment]
Are you still getting that issue?

**Comment by valentinschabschneider** [comment]
i have the same problem

```
Apr 5, 11:42:45 PM: 01JR3YFX error  [render] TypeError: window.matchMedia is not a function
    at Toaster (file:///root/.netlify/edge-functions/render.js:13816:37)
    at Sonner_1 (file:///root/.netlify/edge-functions/render.js:14147:3)
    at _layout (file:///root/.netlify/edge-functions/render.js:14171:3)
    at Root (file:///root/.netlify/edge-functions/render.js:12223:5)
    at render (file:///root/.netlify/edge-functions/render.js:1459:3)
    at Function._render (file:///root/.netlify/edge-functions/render.js:12190:20)
    at render_response (file:///root/.netlify/edge-functions/render.js:22325:34)
    at eventLoopTick (ext:core/01_core.js:177:7)
    at async render_page (file:///root/.netlify/edge-functions/render.js:23263:12)
    at async resolve2 (file:///root/.netlify/edge-functions/render.js:23897:24)

```

**Comment by valentinschabschneider** [comment]
i think this should fix it: https://github.com/denoland/deno/issues/19255#issuecomment-1611175012
